#!/usr/bin/env bash

# https://github.com/onespaceman/menu-calc
# Calculator for use with rofi/dmenu(2)
# Copying to the clipboard requires xclip

usage() {
    echo "    $(tput bold)menu calc$(tput sgr0)
    A calculator for use with Rofi or dmenu(2)
    Basic usage:
    = \"4+2\"
    = \"(4+2)/(4+3)\"
    = \"4^2\"
    = \"sqrt(4)\"
    = \"c(2)\"

    Operations may or may not work if not enclosed in quotations

    The answer can be used for further calculations inside your
    menu application"
    exit
}

case $1 in
    -h|--help) usage ;;
esac

# Path to menu application
if [[ $(which rofi) != *"not found"* ]]; then
    menu="$(which rofi) -dmenu"
elif [[ $(which dmenu) != *"not found"* ]]; then
    menu="$(which dmenu)"
else
    echo "Rofi or dmenu not found"
    exit
fi

answer=$(echo "$@" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')

action=$(echo -e "Copy to clipboard\nClear\nClose" |
$menu -p "= $answer")

case $action in
    "Clear") $0 ;;
    "Copy to clipboard") echo -n "$answer" | xclip ;;
    "Close") ;;
    *) $0 "$answer $action" ;;
esac
